<?php
return array (
  'app' => 'Admin',
  'model' => 'Content',
  'action' => 'default',
  'data' => '',
  'type' => '0',
  'status' => '1',
  'name' => '内容管理',
  'icon' => 'th',
  'remark' => '',
  'listorder' => '30',
  'children' => 
  array (
    array (
      'app' => 'Portal',
      'model' => 'AdminPost',
      'action' => 'default',
      'data' => '',
      'type' => '0',
      'status' => '1',
      'name' => '文章列表',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Portal',
          'model' => 'AdminPost',
          'action' => 'listorders',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '文章排序',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Portal',
          'model' => 'AdminPost',
          'action' => 'top',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '文章置顶',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Portal',
          'model' => 'AdminPost',
          'action' => 'recommend',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '文章推荐',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Portal',
          'model' => 'AdminPost',
          'action' => 'copy',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '文章批量复制',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Portal',
          'model' => 'AdminPost',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '文章管理',
          'icon' => '',
          'remark' => '',
          'listorder' => '1',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Articlecat',
          'action' => 'index',
          'data' => 'id=1',
          'type' => '1',
          'status' => '1',
          'name' => '文章配置',
          'icon' => '',
          'remark' => '',
          'listorder' => '4',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Articlecat',
              'action' => 'add',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加配置',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Articlecat',
              'action' => 'edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '修改配置',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Articlecat',
              'action' => 'delete',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '删除配置',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Portal',
          'model' => 'AdminPost',
          'action' => 'move',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '批量移动',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
        ),
        array (
          'app' => 'Portal',
          'model' => 'AdminPost',
          'action' => 'check',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '文章审核',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
        ),
        array (
          'app' => 'Portal',
          'model' => 'AdminPost',
          'action' => 'delete',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '删除文章',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
        ),
        array (
          'app' => 'Portal',
          'model' => 'AdminPost',
          'action' => 'edit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '编辑文章',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
          'children' => 
          array (
            array (
              'app' => 'Portal',
              'model' => 'AdminPost',
              'action' => 'edit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交编辑',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Portal',
          'model' => 'AdminPost',
          'action' => 'add',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加文章',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
          'children' => 
          array (
            array (
              'app' => 'Portal',
              'model' => 'AdminPost',
              'action' => 'add_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交添加',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
    array (
      'app' => 'Experience',
      'model' => 'AdminEx',
      'action' => 'default',
      'data' => '',
      'type' => '0',
      'status' => '1',
      'name' => '经验管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '1',
      'children' => 
      array (
        array (
          'app' => 'Experience',
          'model' => 'AdminEx',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '经验管理',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Experience',
              'model' => 'AdminEx',
              'action' => 'check',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '经验审核',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Experience',
              'model' => 'AdminEx',
              'action' => 'recommend',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '经验推荐',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Experience',
              'model' => 'AdminEx',
              'action' => 'top',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '经验置顶',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Experience',
              'model' => 'AdminEx',
              'action' => 'delete',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '删除经验',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Experience',
              'model' => 'AdminEx',
              'action' => 'edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '修改经验',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Experience',
              'model' => 'AdminEx',
              'action' => 'add',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加经验',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Experience',
              'model' => 'AdminEx',
              'action' => 'move',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '批量移动',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Experience',
          'model' => 'AdminExTerm',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '经验分类管理',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Experience',
              'model' => 'AdminExTerm',
              'action' => 'add',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加分类',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Experience',
              'model' => 'AdminExTerm',
              'action' => 'edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '修改分类',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Experience',
              'model' => 'AdminExTerm',
              'action' => 'delete',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '删除分类',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Experience',
              'model' => 'AdminExTerm',
              'action' => 'listorders',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '经验分类排序',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Experience',
          'model' => 'EQrelationship',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '经验/问答关联',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Experience',
              'model' => 'EQrelationship',
              'action' => 'edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '修改关联',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Experience',
          'model' => 'EArelationship',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '经验/文章关联',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Experience',
              'model' => 'EArelationship',
              'action' => 'edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '修改关联',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Experience',
          'model' => 'Articlecat',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '经验配置',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Experience',
              'model' => 'Articlecat',
              'action' => 'delete',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '删除配置',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Experience',
              'model' => 'Articlecat',
              'action' => 'edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '修改配置',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Experience',
              'model' => 'Articlecat',
              'action' => 'add',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加配置',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
    array (
      'app' => 'Encyclopedia',
      'model' => 'AdminEn',
      'action' => 'default',
      'data' => '',
      'type' => '0',
      'status' => '1',
      'name' => '百科管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '2',
      'children' => 
      array (
        array (
          'app' => 'Encyclopedia',
          'model' => 'AdminEn',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '百科管理',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Encyclopedia',
              'model' => 'AdminEn',
              'action' => 'delete',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '删除百科',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Encyclopedia',
              'model' => 'AdminEn',
              'action' => 'edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '修改百科',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Encyclopedia',
              'model' => 'AdminEn',
              'action' => 'add',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加百科',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Encyclopedia',
              'model' => 'AdminEn',
              'action' => 'check',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '百科审核',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Encyclopedia',
              'model' => 'AdminEn',
              'action' => 'top',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '百科置顶',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Encyclopedia',
              'model' => 'AdminEn',
              'action' => 'recommend',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '百科推荐',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Encyclopedia',
              'model' => 'AdminEn',
              'action' => 'move',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '批量移动',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Encyclopedia',
          'model' => 'AdminEnTerm',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '百科分类管理',
          'icon' => '',
          'remark' => '',
          'listorder' => '1',
          'children' => 
          array (
            array (
              'app' => 'Encyclopedia',
              'model' => 'AdminEnTerm',
              'action' => 'delete',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '删除分类',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Encyclopedia',
              'model' => 'AdminEnTerm',
              'action' => 'edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '修改分类',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Encyclopedia',
              'model' => 'AdminEnTerm',
              'action' => 'add',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加分类',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Encyclopedia',
              'model' => 'AdminEnTerm',
              'action' => 'listorders',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '百科分类排序',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Encyclopedia',
          'model' => 'Articlecat',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '百科配置',
          'icon' => '',
          'remark' => '',
          'listorder' => '2',
          'children' => 
          array (
            array (
              'app' => 'Encyclopedia',
              'model' => 'Articlecat',
              'action' => 'add',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加配置',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Encyclopedia',
          'model' => 'EErelationship',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '百科/经验关联',
          'icon' => '',
          'remark' => '',
          'listorder' => '3',
          'children' => 
          array (
            array (
              'app' => 'Encyclopedia',
              'model' => 'EErelationship',
              'action' => 'edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '修改关联',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Encyclopedia',
          'model' => 'EQrelationship',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '百科/问答关联',
          'icon' => '',
          'remark' => '',
          'listorder' => '3',
          'children' => 
          array (
            array (
              'app' => 'Encyclopedia',
              'model' => 'EQrelationship',
              'action' => 'edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '修改关联',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Encyclopedia',
          'model' => 'EArelationship',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '百科/文章关联',
          'icon' => '',
          'remark' => '',
          'listorder' => '3',
          'children' => 
          array (
            array (
              'app' => 'Encyclopedia',
              'model' => 'EArelationship',
              'action' => 'edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '修改关联',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
    array (
      'app' => 'Qa',
      'model' => 'AdminQa',
      'action' => 'default',
      'data' => '',
      'type' => '0',
      'status' => '1',
      'name' => '有问必答',
      'icon' => '',
      'remark' => '',
      'listorder' => '3',
      'children' => 
      array (
        array (
          'app' => 'Qa',
          'model' => 'AdminQuestion',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '问答管理',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Qa',
              'model' => 'AdminQuestion',
              'action' => 'edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '修改问题',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Qa',
              'model' => 'AdminQuestion',
              'action' => 'add',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加问题',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Qa',
              'model' => 'AdminQuestion',
              'action' => 'delete',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '删除问题',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Qa',
              'model' => 'AdminAnswer',
              'action' => 'index',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '查看回答',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Qa',
              'model' => 'AdminAnswer',
              'action' => 'add',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '回答问题',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Qa',
              'model' => 'AdminAnswer',
              'action' => 'edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '修改回答',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Qa',
              'model' => 'AdminAnswer',
              'action' => 'delete',
              'data' => '',
              'type' => '1',
              'status' => '1',
              'name' => '删除回答',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Qa',
              'model' => 'AdminQuestion',
              'action' => 'check',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '问题审核',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Qa',
              'model' => 'AdminQuestion',
              'action' => 'top',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '问题置顶',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Qa',
              'model' => 'AdminQuestion',
              'action' => 'recommend',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '问题推荐',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Qa',
              'model' => 'AdminQuestion',
              'action' => 'move',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '问题批量移动',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Qa',
              'model' => 'AdminQuestion',
              'action' => 'count',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '重新统计回答数',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Qa',
          'model' => 'AdminQaTerm',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '分类管理',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Qa',
              'model' => 'AdminQaTerm',
              'action' => 'add',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加分类',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Qa',
              'model' => 'AdminQaTerm',
              'action' => 'edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '修改分类',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Qa',
              'model' => 'AdminQaTerm',
              'action' => 'delete',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '删除分类',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Qa',
          'model' => 'Articlecat',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '问答配置',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Qa',
              'model' => 'Articlecat',
              'action' => 'add',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加配置',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Qa',
              'model' => 'Articlecat',
              'action' => 'edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '修改配置',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Qa',
              'model' => 'Articlecat',
              'action' => 'delete',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '删除配置',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Qa',
          'model' => 'Relationship',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '问答/文章关联',
          'icon' => '',
          'remark' => '',
          'listorder' => '1',
          'children' => 
          array (
            array (
              'app' => 'Qa',
              'model' => 'Relationship',
              'action' => 'edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '修改关联',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
    array (
      'app' => 'Portal',
      'model' => 'AdminTerm',
      'action' => 'index',
      'data' => '',
      'type' => '0',
      'status' => '1',
      'name' => '分类管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '4',
      'children' => 
      array (
        array (
          'app' => 'Portal',
          'model' => 'AdminTerm',
          'action' => 'listorders',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '文章分类排序',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Portal',
          'model' => 'AdminTerm',
          'action' => 'delete',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '删除分类',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
        ),
        array (
          'app' => 'Portal',
          'model' => 'AdminTerm',
          'action' => 'edit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '编辑分类',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
          'children' => 
          array (
            array (
              'app' => 'Portal',
              'model' => 'AdminTerm',
              'action' => 'edit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交编辑',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Portal',
          'model' => 'AdminTerm',
          'action' => 'add',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加分类',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
          'children' => 
          array (
            array (
              'app' => 'Portal',
              'model' => 'AdminTerm',
              'action' => 'add_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交添加',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
    array (
      'app' => 'Portal',
      'model' => 'AdminPage',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '页面管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '5',
      'children' => 
      array (
        array (
          'app' => 'Portal',
          'model' => 'AdminPage',
          'action' => 'listorders',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '页面排序',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Portal',
          'model' => 'AdminPage',
          'action' => 'delete',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '删除页面',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
        ),
        array (
          'app' => 'Portal',
          'model' => 'AdminPage',
          'action' => 'edit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '编辑页面',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
          'children' => 
          array (
            array (
              'app' => 'Portal',
              'model' => 'AdminPage',
              'action' => 'edit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交编辑',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Portal',
          'model' => 'AdminPage',
          'action' => 'add',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加页面',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
          'children' => 
          array (
            array (
              'app' => 'Portal',
              'model' => 'AdminPage',
              'action' => 'add_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交添加',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
    array (
      'app' => 'Api',
      'model' => 'Guestbookadmin',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '所有留言',
      'icon' => '',
      'remark' => '',
      'listorder' => '6',
      'children' => 
      array (
        array (
          'app' => 'Api',
          'model' => 'Guestbookadmin',
          'action' => 'delete',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '删除网站留言',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Comment',
      'model' => 'Commentadmin',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '评论管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '7',
      'children' => 
      array (
        array (
          'app' => 'Comment',
          'model' => 'Commentadmin',
          'action' => 'delete',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '删除评论',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Comment',
          'model' => 'Commentadmin',
          'action' => 'check',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '评论审核',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Recycle',
      'action' => 'default',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '回收站',
      'icon' => '',
      'remark' => '',
      'listorder' => '8',
      'children' => 
      array (
        array (
          'app' => 'Portal',
          'model' => 'AdminPost',
          'action' => 'recyclebin',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '文章回收',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Portal',
              'model' => 'AdminPost',
              'action' => 'restore',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '文章还原',
              'icon' => '',
              'remark' => '',
              'listorder' => '1000',
            ),
            array (
              'app' => 'Portal',
              'model' => 'AdminPost',
              'action' => 'clean',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '彻底删除',
              'icon' => '',
              'remark' => '',
              'listorder' => '1000',
            ),
          ),
        ),
        array (
          'app' => 'Api',
          'model' => 'guestbookadmin',
          'action' => 'recyclebin',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '留言回收',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Comment',
          'model' => 'Commentadmin',
          'action' => 'recyclebin',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '评论回收',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Qa',
          'model' => 'AdminQuestion',
          'action' => 'recyclebin',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '问题回收',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Qa',
              'model' => 'AdminQuestion',
              'action' => 'restore',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '问题还原',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Qa',
              'model' => 'AdminQuestion',
              'action' => 'clean',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '彻底删除',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Encyclopedia',
          'model' => 'AdminEn',
          'action' => 'recyclebin',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '百科回收',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Encyclopedia',
              'model' => 'AdminEn',
              'action' => 'restore',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '百科还原',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Encyclopedia',
              'model' => 'AdminEn',
              'action' => 'clean',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '彻底删除',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Experience',
          'model' => 'AdminEx',
          'action' => 'recyclebin',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '经验回收',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Experience',
              'model' => 'AdminEx',
              'action' => 'restore',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '经验还原',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Experience',
              'model' => 'AdminEx',
              'action' => 'clean',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '彻底删除',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Portal',
          'model' => 'AdminPage',
          'action' => 'recyclebin',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '页面回收',
          'icon' => '',
          'remark' => '',
          'listorder' => '1',
          'children' => 
          array (
            array (
              'app' => 'Portal',
              'model' => 'AdminPage',
              'action' => 'clean',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '彻底删除',
              'icon' => '',
              'remark' => '',
              'listorder' => '1000',
            ),
            array (
              'app' => 'Portal',
              'model' => 'AdminPage',
              'action' => 'restore',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '页面还原',
              'icon' => '',
              'remark' => '',
              'listorder' => '1000',
            ),
          ),
        ),
      ),
    ),
  ),
);